version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong

  kong:
    image: kong
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=db
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "7946:7946"
      - "7946:7946/udp"
    depends_on:
      - db

  dashboard:
    image: pgbi/kong-dashboard
    ports:
      - "8080:8080"
    depends_on:
      - kong
